export const POST_LIST_REQUEST = 'POST_LIST_REQUEST'
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const POST_LIST_FAIL = 'POST_LIST_FAIL'


export const CREATE_NEW_POST_REQUEST = 'CREATE_NEW_POST_REQUEST'
export const CREATE_NEW_POST_SUCCESS = 'CREATE_NEW_POST_SUCCESS'
export const CREATE_NEW_POST_FAIL = 'CREATE_NEW_POST_FAIL'